Subs/Models/Entity/Comment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity.Migrations.Model;
using System.Linq;
using System.Web;

namespace Subs.Models.Entity
{
    public class Comment
    {
        // Eigindi fyrir umsagnir --------------------------------------------------------
        [Key]       // Frumlykill
        public int CommentId { get; set; }

        [Required]
        // Ekki nullable
        public string sCommenterUsername { get; set; }
        [Required]  // Ekki nullable
        public string sCommentText { get; set; }
        // Synir bara dagsetningu - tekur ut klukkuna
        //[DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime? dCommentDate { get; set; }
        // -------------------------------------------------------------------------------

        // Adkomulyklar ------------------------------------------------------------------
        // (many-to-one) - Request a lista af Commentum
        [Required]
        public virtual Request Request { get; set; }
        // (many-to-one) - SubFile alista af Commentum
        [Required]
        public virtual SubFile SubFile { get; set; }
        // (many-to-one) - ApplicationUser a lista af Commentum
        [Required]
        public virtual ApplicationUser ApplicationUser { get; set; }
    }
}

Subs/Models/ViewModel/CommentViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using Subs.App_Data.DataAccessLayer;
using Subs.Models.Entity;

namespace Subs.Models.ViewModel
{
    public class CommentViewModel
    {
        //public IEnumerable<Entity.Comment> CommentData { get; set; }
        //public IEnumerable<Entity.Request> RequestData { get; set; }
        //public IEnumerable<Entity.SubFile> SubFileData { get; set; }


        //// Eigindi fyrir umsagnir --------------------------------------------------------
        //public int CommentId { get; set; }
        //public string sCommenterUsername { get; set; }
        //public string sCommentText { get; set; }
        //// Synir bara dagsetningu - tekur ut klukkuna
        //[DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        //public DateTime? dCommentDate { get; set; }
        //// -------------------------------------------------------------------------------

        //// Adkomulyklar ------------------------------------------------------------------
        //// (many-to-one) - Request a lista af Commentum
        //[Required]
        //public virtual Request Request { get; set; }
        //// (many-to-one) - SubFile alista af Commentum
        //[Required]
        //public virtual SubFile SubFile { get; set; }
        //// (many-to-one) - ApplicationUser a lista af Commentum
        //[Required]
        //public virtual ApplicationUser ApplicationUser { get; set; }


        public int CommentId { get; set; }
        //public string sCommenterUsername { get; set; }
        public string sCommentText { get; set; }

    }
}

Subs/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Subs.Models.Entity;
using Subs.Models.Interface;
using Subs.Models.Repository;
using Subs.Models.ViewModel;

namespace Subs.Controllers
{
    public class CommentController : Controller 
    {
        // Tennging i gagnagrunn - Tekin ut thegar repos. koma inn
        //private SubDataContext db = new SubDataContext();

        // Tengingar i gagnagrunn ---------------------------------------
        // Thetta er tenging vid Interface klasann sem tengist
        //   svo vid Repository sem tengist svo vid gagnagrunn 
        private ICommentRepository Comment_m_repository = null;

        // Smidur fyrir tengingar i Repositories
        public CommentController()
        {
            Comment_m_repository = new CommentRepository();
        }
        // --------------------------------------------------------------

        // Thetta er tilbuid fyrir mock-database ------------------------
        // Notad vid einingaprofanir
        //public HomeController(IClientRepository rep)
        //{
        //    m_repository = rep;
        //}
        // --------------------------------------------------------------

        // Her fyrir nedan koma Viewin ----------------------------------

        // Skoda umsogn - sott med ID
        [HttpGet]
        public ActionResult CommentInfo(int? iId)
        {
            // Saekja skra eftir ID
            var vComment = Comment_m_repository.GetCommentById(iId);
           
            // Setja umbedna skra inn i ViewModel
            CommentViewModel model = new CommentViewModel
            {
                CommentId = vComment.CommentId,
                sCommentText = vComment.sCommentText,
            };
            return View(model);
        } 
    }
}

Subs/Controllers/RequestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Subs.Models;
using Subs.Models.Interface;
using Subs.Models.Repository;
using Subs.Models.Entity;
using Subs.Models.ViewModel;

namespace Subs.Controllers
{
	public class RequestController : Controller
	{
		// Tennging i gagnagrunn - Tekin ut thegar repos. koma inn
		//private SubDataContext db = new SubDataContext();

		// Tengingar i gagnagrunn ---------------------------------------
		// Thetta er tenging vid Interface klasann sem tengist
		//   svo vid Repository sem tengist svo vid gagnagrunn 
		private IRequestRepository Request_m_repository = null;
		private ISubFileRepository SubFile_m_repository = null;

		// Smidur fyrir tengingar i Repositories
		public RequestController()
		{
			Request_m_repository = new RequestRepository();
			SubFile_m_repository = new SubFileRepository();
		}
		// --------------------------------------------------------------

		// Thetta er tilbuid fyrir mock-database ------------------------
		// Notad vid einingaprofanir
		//public HomeController(IClientRepository rep)
		//{
		//    m_repository = rep;
		//}
		// --------------------------------------------------------------

		// Her fyrir nedan koma Viewin ----------------------------------

		public ActionResult RequestSearch()
		{
			ViewBag.Message = "Beiðni-Leit";
			var vCategoryModel = Request_m_repository.GetRequestsByCategory();

			return View(vCategoryModel);
		}

		[HttpGet]
		public ActionResult RequestInfo(int? id)
		{   //ekki hægt að fara eftir kóðareglum með int? id sem er strongly typed
			ViewBag.Message = "Skráarupplýsingar/Niðurhal";

			var vCategoryModel = Request_m_repository.GetRequestsByCategory();

			var vResult = (from Request in vCategoryModel
						  where Request.RequestId == id
						  orderby Request.sTitle ascending 
						  select Request).SingleOrDefault();
			if (id.HasValue)
			{
				return View(vResult);
			}
			return View();
		}

		[HttpGet]
		public ActionResult RequestSubmit()
		{
			var vModel = new RequestViewModel();
			return View(vModel);
		}

		[HttpPost]
		public ActionResult RequestSubmit(RequestViewModel model, Request request)
		{
			if (ModelState.IsValid)
			{
				if (request != null)
				{
					Request_m_repository.InsertRequest(request);
					Request_m_repository.SaveChanges();
					
					return RedirectToAction("RequestInfo", new { id = request.RequestId });
				}
			}

			return View();
		}
	}
}

Subs/Views/Shared/_Comment.cshtml
@model IEnumerable<Subs.Models.Entity.Comment>
@{
    if (Model != null)
    {
        foreach (var comment in Model)
        {
            <form>
                <fieldset>
                    @*---------------Nær í netendanafn og comment á beiðninni----*@
                    <legend> @Html.DisplayFor(modelitem => comment.sCommenterUsername)</legend>
                    @Html.DisplayFor(modelItem => comment.sCommentText)
                </fieldset>
            </form>
        }
    }
}

Subs/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @*------------Titill á Síðuna-------------*@
    <div id="head-top">
        <h1> Subs}|⁞ǁ⁞|{Text </h1>
    </div>
    @*---------------Valslá------------------*@
    <div id="head">
        <div id="nav">
            <ul>
                <li>@Html.ActionLink("Heim", "Index", "Home", null, new { @class = "tab", hidefocus = "hidefocus" })</li>
                <li>@Html.ActionLink("Beiðnir", "RequestSearch", "Request", null, new { @class = "tab" })</li>
                <li>@Html.ActionLink("Um okkur", "About", "Home", null, new { @class = "tab" })</li>
                <li>@Html.ActionLink("Leiðbeiningar", "Instructions", "Home", null, new { @class = "tab" })</li>
            </ul>
        </div>
    </div>
    @*---------------Kall í innskráningar hlutan----------*@
    @Html.Partial("_LoginPartial")
    @*------------------Efnið á hverri síðu er 'Renderað' hérna----------------*@
    <div id="container" class="container body-content">
        @RenderBody()
    </div>
    @*--------------------Fótur síðunnar-------------------*@
    <div class="footer-bottom">
        <div class="footer-content">
            <p id="footer-recomend"> Við mælum með <a href="http://www.videolan.org/vlc/index.html">VLC</a></p>
            <p> Við berum ekki ábyrgð á höfundavörðu efni né innihaldi skráa sem deilt er í gegnum síðuna </p>
        </div>
    </div>

    <footer></footer>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>