Subs/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using Subs;
using Subs.App_Data.DataAccessLayer;
using Subs.Models.Interface;
using Subs.Models.Repository;
using Subs.Models.Entity;
using Subs.Models.ViewModel;
using Subs.Migrations;
using System.IO;



namespace Subs.Controllers
{
    public class HomeController : Controller
    {
        // Tennging i gagnagrunn - Tekin ut thegar repos. koma inn
        //private SubDataContext db = new SubDataContext();

        // Thetta eru tengingar vid Interface klasana sem tengjast
        //   svo vid Repository sem tengjast svo vid gagnagrunn 
        //private IClientRepository Client_m_repository = null;
        private ICommentRepository Comment_m_repository = null;
        private IRequestRepository Request_m_repository = null;
        private ISubFileRepository SubFile_m_repository = null;

        // Smidur fyrir tengingar i Repositories
        public HomeController()
        {
            //Client_m_repository  = new ClientRepository();
            Comment_m_repository = new CommentRepository();
            Request_m_repository = new RequestRepository();
            SubFile_m_repository = new SubFileRepository();
        }

        // Thetta er tilbuid fyrir mock-database ------------------------
        // Notad vid einingaprofanir
        //public HomeController(IClientRepository rep)
        //{
        //    m_repository = rep;
        //}
        // --------------------------------------------------------------

        public ActionResult Index() /*Search  leitar í DB */
        {            
            var vListModel = SubFile_m_repository.GetSubFiles();

            var result = from s in vListModel
                orderby s.sTitle ascending
                select s;

            return View(result);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Um okkur";

            return View();
        }

        public ActionResult Instructions()
        {
            ViewBag.Message = "Leiðbeiningar";

            return View();
        }
        public ActionResult IndexSearch()  
        {/*Náðist ekki að útfærast*/
            ViewBag.Message = "Leit";

            return View();
        }

    }
}

Subs/Controllers/SubFileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using Subs.Models;
using Subs.Models.Entity;
using Subs.Models.Interface;
using Subs.Models.Repository;
using Subs.Models.ViewModel;

namespace Subs.Controllers
{
	public class SubFileController : Controller
	{
		// Tengingar i gagnagrunn ---------------------------------------
		// Thetta er tenging vid Interface klasann sem tengist
		//   svo vid Repository sem tengist svo vid gagnagrunn 
		private ISubFileRepository SubFile_m_repository = null;

		// Smidur fyrir tengingar i Repositories
		public SubFileController()
		{
			SubFile_m_repository = new SubFileRepository();
		}
		// --------------------------------------------------------------

		// Thetta er tilbuid fyrir mock-database ------------------------
		// Notad vid einingaprofanir
		//public HomeController(IClientRepository rep)
		//{
		//    m_repository = rep;
		//}
		// --------------------------------------------------------------

		// Her fyrir nedan koma Viewin ----------------------------------

		public ActionResult Upload()
		{
			var vModel = new SubFileViewModel();
			return View(vModel);
		}

		// Senda inn skra - tekur inn ViewModel
		[HttpPost]
		public ActionResult Upload(SubFileViewModel vModel)
		{
			SubFile SubFile = new SubFile();
			int iMaxContentLength = 1024 * 1024 * 1; //1 MB
			string[] AllowedFileExtensions = new string[] { ".srt", ".SRT" };
			
			if (!ModelState.IsValid) {
				ViewBag.Message = "Enginn skrá var valinn";
				return View(vModel); 
			}
			/* passar að skráin sé ekki tóm*/
			if (vModel.sFilePath == null)
			{   
				ViewBag.Message = "Engin skrá var valin";
				return View(vModel); 
			}
			/* passar skráar endingu sé .srt eða .SRT*/
			else if (!AllowedFileExtensions.Contains(vModel.sFilePath.FileName.Substring(vModel.sFilePath.FileName.LastIndexOf('.'))))
			{
				ViewBag.Message = "Skráin þarf að vera af gerðinni: " + string.Join(", ", AllowedFileExtensions);
				return View(vModel); ;
			}
			/* passar að skráin sé ekki of stór ekki viss með hversu stór hún þarf að vera setti 1mb*/
			else if (vModel.sFilePath.ContentLength > iMaxContentLength)
			{
				ViewBag.Message = "Skráin má ekki vera stærri en  : " + (iMaxContentLength / 1024).ToString() + "MB";
				return View(vModel); 
			}
			/* sendir gögn í grunn*/
			byte[] bUploadFile = new byte[vModel.sFilePath.InputStream.Length];
			vModel.sFilePath.InputStream.Read(bUploadFile, 0, bUploadFile.Length);

			SubFile.sTitle = vModel.sFilePath.FileName;
			SubFile.sFilePath = bUploadFile;
			 SubFile.sSubType = vModel.sSubType;
			 SubFile.sSubLanguage = vModel.sSubLanguage;
			 SubFile.sSubDescription = vModel.sSubDescription;
			 SubFile.sGenre = vModel.sGenre;
			 SubFile.sFileUserName = vModel.sFileUserName;
		  
			// Setja skrár i gagnagrunn
			SubFile_m_repository.InsertSubFile(SubFile);
			 // Vista breytingar i gagnagrunni
			SubFile_m_repository.SaveChanges();

			ViewBag.Message = "Skrá hefur verið hlaðið upp - Takk fyrir";
					
			return RedirectToAction("Index", "Home");
			//return Redirect("Upload");
		}
		// Skoda upplysingar um skra - sott med ID
		[HttpGet]
		public ActionResult FileInfo(int? id)
		{   //ekki hægt að fara eftir kóðareglum með int? id sem er strongly typed
			// Saekja skra eftir ID
			var file = SubFile_m_repository.GetSubFilesById(id);
			// Setja umbedna skra inn i ViewModel
			//if (id.HasValue)
			//{
				SubFileViewModel model = new SubFileViewModel
				{
					SubFileId = file.SubFileId,
					sTitle = file.sTitle,
					sFileUserName = file.sFileUserName,
					sSubLanguage = file.sSubLanguage,
					sSubType = file.sSubType,
					sGenre = file.sGenre,
					//dSubDate = file.dSubDate,
					sPicture = file.sPicture,
					sSubDescription = file.sSubDescription,
					iUpVote = file.iUpVote
				};
				return View(model);
		}

		// Saekja skra
		[HttpGet]
		public FileContentResult FileDownload(int? id)
		{
			// Tekur inn byteArray
			byte[] bFileData;
			// Skraarnafn
			string sFileName;

			// Saekja skra eftir ID
			SubFile fileRecord = SubFile_m_repository.GetSubFilesByCategory().Find(id);

			bFileData = (byte[])fileRecord.sFilePath.ToArray();
			sFileName = fileRecord.sTitle;

			return File(bFileData, "text", sFileName);
		}
	}
}

Subs/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<div class="about">
    <div id="about-text">
        @*-------------Stutt lýsing á tilgangi síðunnar----------*@
        <h2>Um okkur</h2>
        <p>
            Síðan er gerð í þeim tilgangi að leyfa fólki að ná í texta skrár, leiðrétta og
            jafnvel spreyta sig á að búa til skjátextaskrá og hlaða henni inná síðuna. Til að
            hafa samband við vefstjórnendur er hægt að senda póst á vefföng þeirra. Síðan er
            verður ekki með vefauglýsingar svo lengi sem við græðum nægan pening á ykkur frá
            styrkjum.
        </p>
        @*--------Reglur síðunar--------*@
        <h2>Reglur</h2>
        <h3>Almennar reglur</h3>
        <ol>
            <li>Stjórnendur meiga breita eða búa til reglur án fyrirvara </li>
            <li>Reglur er eithvað sem má fylgja en þarf ekki</li>
            <li>Gerðu eithvað rétt</li>
            <li>Bannað að senda okkur mail</li>
        </ol>
        <h3>Notenda reglur</h3>
        <ol>
            <li>Ekki vera dick</li>
        </ol>
    </div>
    @*-------------Hvernig hægt er að hafa samband---------------*@
    <div id="about-list">
        <dl>
            <dt>Sveinbjorn Berent B</dt>
            <dd>sveinbjorn13@ru.is </dd>
            <dt>Heiðar Freyr</dt>
            <dd>freyr1980@gmail.com</dd>
            <dt>Guðmundur Rúnar</dt>
            <dd>gummire@gmail.com</dd>
            <dt>Kjartan Kjartansson</dt>
            <dd>kjartan607@gmail.com</dd>
            <dt>Kevin Freyr Leósson</dt>
            <dd>kevinfreyr@gmail.com</dd>
            <dt>Sigurður Páll Guttormsson</dt>
            <dd>sigurdurpallguttormson@gmail.com</dd>
        </dl>
    </div>
    <div id="about-rest">

        @*------------------Skilmálar síðunnar-------------*@
        <h2>Skilmálar</h2>
        <div id="useragrement">
            <p>
                Rosa mikilvægt bla bla bla, ekki til að selja, nema við græðum líka.
                ekki í eigu fyrirtækis nema þú viljir kaupa. peningar reglur reglur samþykkir
                að gefa nýra.
            </p>
        </div>
    </div>
</div>

Subs/Views/Home/FileForm.cshtml
@{
    ViewBag.Title = "Senda inn skrá";
}

<!-- Byrjum á því að gera brauðslóð (breadcrumb) til að upplýsa notandann hvar hann er staddur á síðunni. -->

<div class="file-form">
<div id="Breadcrumb">
    <a href="/Home/">Heim</a> > <a href="/Home/Search">Beiðni</a> > Senda inn skrá
</div>

<!-- Svæði þar sem notandi skráir inn Nafn, tungumál og slóða á mynd. -->

<div id="upload">
        <form>
            <fieldset>
                <legend>Senda inn skrá</legend>
                <div class="room">
                    Nafn <input class="textbox-room" type="text" name="name"><br>
                </div>
                <div class="room">
                    Tungumál <input class="textbox-room" type="text" name="language"><br>
                </div>
                <div class="room">
                    Slóð á mynd <input class="textbox-room" type="text" name="url"><br>
                </div>

            <!-- Hér eru radiotakkar þar sem valið er annaðhvort mynd eða þáttur. -->

                <div class="room">
                    Gerð
                    <input id="radioroom" type="radio" name="type" value="movie">Mynd
                    <input id="radioroom" type="radio" name="type" value="tv-show">Þáttur

            </div

            <!-- Dropdown listi til að velja flokk skráar. -->

            <div>
            <select name="Categories" id="Categories">
                <option value="valmynd">--Velja flokk--</option>
                <option value="barnaefni">Barnaefni</option>
                <option value="drama">Drama</option>
                <option value="gaman">Gaman</option>
                <option value="hrollvekja">Hrollvekja</option>
                <option value="spenna">Spenna</option>
            </select>


                </div>

            <!-- Textarea fyrir nánari lýsingu á skránni. -->

                <p>Nánar</p> <textarea rows="5" cols="75"></textarea><br>

            <!-- Takkar þar sem notandi getur sent inn skrá (submit) eða hætta við þar sem hann er redirectaður inná forsíðuna. -->

            <div>
                    <input type="button" name="submit" value="Submit">
                    <input type="button" name="cancel" value="Hætta vid">
                </div>
            </fieldset>
        </form>

    </div>
</div>

Subs/Views/Home/Index.cshtml
@model IEnumerable<Subs.Models.Entity.SubFile>

@{
    ViewBag.Title = "Home Page";
}

<div class="home-page">
    @*---------------Leitarkassi fyrir leit á skrám á forsíðunni--------------*@
    <form id="searchbox" action="">
        <input id="search" type="text" placeholder="Leita"> <!-- Leitarkassinn -->
        <select name="Categories" id="Categories">
            <option value="valmynd">--Velja flokk--</option> <!-- Dropdown listi til að velja flokk -->
            <option value="barnaefni">Barnaefni</option>
            <option value="drama">Drama</option>
            <option value="gaman">Gaman</option>
            <option value="hrollvekja">Hrollvekja</option>
            <option value="spenna">Spenna</option>
        </select>
        <input id="submit" type="submit" value="Leita">  <!-- Leitar takki -->
    </form>
    @*--------------Tafla sem að birtir Nýjustu skrárnar--------------------*@
    <div id="center">
        <table class="table-responsive table table-bordered table-hover ">
            <caption><h3>SRT. Skrár</h3></caption>
            <thead>
                <tr>
                    <th>Titill</th>
                    <th>Gerð</th>
                    <th>Þýðing</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td> @Html.ActionLink(item.sTitle, "FileInfo", "SubFile", new { id = item.SubFileId }, null) </td>
                        <td> @item.sSubType </td>
                        <td> @item.sSubLanguage </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

        

Subs/Views/Home/Index22.cshtml
@model IEnumerable<Subs.Models.Entity.SubFile>

@{
    ViewBag.Title = "Home Page";
}


<div class="home-page">
<!-- Hér búum við til leitarkassa á forsíðunni með "Search" takka sem nær í gögn úr gagnagrunninum.
    Ásamt því að vera með dropdown lista til að velja flokk.   -->
<form id="searchbox" action="">
    <input id="search" type="text" placeholder="Leita"> <!-- Leitarkassi -->
    <select name="Categories" id="Categories">
        <option value="valmynd">--Velja flokk--</option> <!-- Dropdown listi til að velja flokk -->
        <option value="barnaefni">Barnaefni</option>
        <option value="drama">Drama</option>
        <option value="gaman">Gaman</option>
        <option value="hrollvekja">Hrollvekja</option>
        <option value="spenna">Spenna</option>
    </select>
    <input id="submit" type="submit" value="Search">  <!-- Search takki -->
</form>

<!-- Tafla sem að birtir vinsælustu skrárnar. Notum Razor kóðun til að sækja þær úr gagnagrunninum. -->
<div id="center">
    <table class="table-responsive table table-bordered table-hover table-left">
        <caption><h3>Vinsælast</h3></caption>
        <thead>
            <tr>
                <th>Titil</th>
                <th>Tungumál</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td> @Html.ActionLink(item.sTitle, "FileInfo", new { id = item.iSubFileId })</td>
                   @*<td> @Html.ActionLink(item.sUsername, "info", new { id = item.sUsername }) </td>*@
                    <td> @item.sSubLanguage </td>
                </tr>
            }
        </tbody>
    </table>
    <!-- Tafla sem að birtir nýjustu skrárnar. Notum Razor kóðun til að ná í vinsælustu skrárnar úr gagnagrunninum. -->

    <table class="table-responsive table table-bordered table-hover table-right">
        <caption><h3>Nýjast</h3></caption>
        <thead>
            <tr>
                <th>Titil</th>
                <th>Tungumál</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td> @Html.ActionLink(item.sTitle, "FileInfo", new { id = item.iSubFileId })</td>
                    <td> @item.sSubLanguage </td>
                </tr>
            }


        </tbody>
    </table>
</div>
</div>

Subs/Views/Home/IndexSearch.cshtml
@model Subs.Models.Entity.SubFile

<div>
    <h4>SubFile</h4>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.sTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.sSubLanguage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sSubLanguage)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.sSubType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sSubType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.sGenre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sGenre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dSubDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dSubDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.sPicture)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sPicture)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.sSubDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sSubDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.sFilePath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sFilePath)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.iUpVote)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.iUpVote)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>

Subs/Views/Home/Instructions.cshtml
@{
    ViewBag.Title = "Instructions"; 
}

    <!-- Aðferðir hvernig á að nota .srt skrá í VLC -->
<div class="instructions">
    <div id="use-srt">
        <h1>Leiðbeiningar</h1>
        <h2>Notkun á .srt skrám í VLC:</h2>
        <ul>
            <li>
                Aðferð 1.
                <ol>
                    <li>Búðu til möppu undir myndskrána og .srt skrána.</li>
                    <li>Passaðu að báðar skrár hafi alveg sama nafn (fyrir utan skráarendinguna).</li>
                    <li>Opnaðu síðan myndskrána með VLC.</li>
                </ol>
            </li>
            <li>
                Aðferð 2.
                <ol>
                    <li>Finndu myndskrána og .srt skrána. (hér þarf ekki að passa að þær hafi sama nafn)</li>
                    <li>Veldu báðar skrárnar og dragðu þær saman yfir í VLC.</li>
                </ol>
            </li>
            <li>
                Aðferð 3.
                <ol>
                    <li>Opnaðu VLC.</li>
                    <li>Opnaðu File->Advanced open file.</li>
                    <li>Við "Choose a file" skaltu smella á "Browse..." og finna myndskrána.</li>
                    <li>Hakaðu við "Load subtitle file:", smelltu á "Choose..." og veldu .srt skrána.</li>
                    <li>Smelltu síðan á "Open" til að spila myndina.</li>
                </ol>
            </li>
        </ul>
    </div>
    <!-- Leiðbeiningar hvernig á að búa til .srt skrá ásamt skjáskot hvernig það er gert. -->
    <div id="make-srt">

        <div class="make-srt-list">
            <h2>Að búa til .srt skrá:</h2>
            <ol>
                <li>Opnaðu nýtt skjal í textavinnslu forriti (eins og t.d. Notepad eða TextEdit).</li>
                <li>Texti sem á að birtast á skjánum þarf að hafa 3 atriði í skjalinu:</li>
                <li>
                    <ol type="a">
                        <li>Tölu sem að hækkar um einn með hverju textabroti. (1 fyrir fyrsta texta sem birtist, 2 fyrir þann næsta,                            o.s.frv.).</li>
                        <li>Það tímabil þar sem að textinn á að birtast, skipt með tvípunktum upp í klukkustundir, mínútur og sekúndur. Á milli tímanna skal vera ör búin til með tveimur bandstrikum og hægri gogg (-->).</li>
                        <li>Textan sjálfan.</li>
                    </ol>
                </li>
                <li>Að lokum skal vista skrána með skráarendingunni ".srt".</li>
            </ol>
        </div>
        @*-------------Dæmi mynd------------*@
        <div id="example">
            <b>Dæmi um .srt skjal:</b> <br>
            <img src="http://i.imgur.com/kSJPn2e.png">
        </div>
    </div>
</div>

Subs/Views/Home/MostPopular.cshtml
@model IEnumerable<Subs.Models.Entity.SubFile>

@{
    ViewBag.Title = "MostPopular";
}

    <!-- Tafla sem að birtir vinsælustu skrárnar. Notum Razor kóðun til að sækja þær úr gagnagrunninum. -->
 
        <table class="table-responsive table table-bordered table-hover table-left">
            <caption><h3>Vinsælast</h3></caption>
            <thead>
                <tr>

                    <th>Titill</th>
                    <th>Gerð</th>
                    <th>Þýðing</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
{
    <tr>
        <td> @Html.ActionLink(item.sTitle, "FileInfo", "SubFile", new { id = item.SubFileId }, null) </td>
        @*<td> @Html.ActionLink(item.sTitle, "FileInfo", new { id = item.SubFileId }) </td>*@
        <td> @item.sSubType </td>
        <td> @item.sSubLanguage </td>
    </tr>
}
            </tbody>
        </table>
      

Subs/Views/Home/NewForm.cshtml
@{
    ViewBag.Title = "NewForm";
}

    <div class="breadcrumb">
    <p><a href="/Home/">Heim</a> > <a href="/Home/Search">Beiðni</a> > Ný beiðni</p>
    </div>
    <div id="upload">
        <form>
            <fieldset>
                <legend>Nýbeiðni</legend>
                <div class="room">
                    Nafn <input class="textbox-room" type="text" name="name"><br>
                </div>
                <div class="room">
                    Tungumál <input class="textbox-room" type="text" name="language"><br>
                </div>
                <div class="room">
                    Slóð á mynd <input class="textbox-room" type="text" name="url"><br>
                </div>
                <div class="room">
                    Gerð
                    <input id="radioplass" type="radio" name="type" value="movie">Mynd
                    <input id="radioplass" type="radio" name="type" value="tv-show">Þáttur
                </div>
                <div>
                    <select id="SearchMenu" name="Category">
                        <option value="menu">--Velja flokk--</option>
                        <option value="cartoon">Barnaefni</option>
                        <option value="drama">Drama</option>
                        <option value="comedy">Gaman</option>
                        <option value="thriller">Hrollvekja</option>
                        <option value="action">Spenna</option>
                    </select>

                </div><br />

                <div>
                    <p id="Boost">Nánar</p> <textarea id="Boost" rows="20" cols="50"></textarea><br>
                </div>
                <div>
                    <input type="button" name="submit" value="Submit">
                    <input type="button" name="cancel" value="Hætta vid">
                </div>
            </fieldset>
        </form>

    </div>

Subs/Views/Home/RequestUpload.cshtml
@{
    ViewBag.Title = "Request Upload";
}

<h2>RequestUpload</h2>

Subs/Views/Home/Search.cshtml
@{
    ViewBag.Title = "Beiðni-Leit";
}

<!-- Byrjum á því að gera brauðslóð (breadcrumb) til að upplýsa notandann hvar hann er staddur á síðunni. -->

    <div class="Breadcrumb">
        <p><a href="/Home/">Heim</a> > Beiðni</p>
    </div>
     
<!-- Búum til leitarkassa þar sem notandinn getur leitað að beiðnum. Hann getur einnig gert Nýja beiðni með takkanum "Ný beiðni". -->

<form id="searchbox" action="">
    <input id="search" type="text" placeholder="Leita">
    <input type="submit" value="Leita">
    <input type="submit" value="Ný beiðni">
</form>

<!-- ÞARF AÐ KÓÐA ÞETTA VIÐ DATABASE -->

    <center>
        <textarea rows="30" cols="50">
            Niðurstöður skrár
        </textarea>
        <textarea rows="30" cols="50">
            Vinsælast
        </textarea>
    </center>

Subs/Views/Home/upload.cshtml
@model Subs.Models.Entity.SubFile

<form action="" method="post" enctype="multipart/form-data">

    <label for="file">Filename:</label>
    <input type="file" name="file" id="file" />

    <input type="submit" />
</form>